server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3320/hotel_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    admin:
      auto-create: true
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

