server:
  port: 8081

spring:
  application:
    name: hotel-service
  datasource:
    url: jdbc:mysql://localhost:3320/hotel_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
