server:
  port: 8082

spring:
  application:
    name: search-consumer

  kafka:
    bootstrap-servers: kafka:9093
    consumer:
      group-id: search-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.ko.hotel.entity.Hotel
      auto-offset-reset: earliest

  elasticsearch:
    uris: http://elasticsearch:9200

logging:
  level:
    org.springframework.data.elasticsearch: DEBUG
