server:
  port: 8082

spring:
  application:
    name: search-consumer

  data:
    elasticsearch:
      repositories:
        enabled: true

  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: search-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.ko.hotel.entity.Hotel
      auto-offset-reset: earliest

  elasticsearch:
    uris: http://localhost:9200


  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org.springframework: DEBUG

elasticsearch:
  mapping:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  repositories:
    enabled: true